<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageId>YellowDogMan.Elements.Style</PackageId>
    <Description>Shared build and code style defaults for Yellow Dog Man Studios / Resonite projects.</Description>

    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <DevelopmentDependency>true</DevelopmentDependency>
  </PropertyGroup>

  <ItemGroup>
    <!-- We MUST package these files with their full NugetPackage Name, they are named without the prefix in this repo for ease of use.-->
    <None Include="Elements.Style.props"
          Pack="true" PackagePath="buildTransitive\YellowDogMan.Elements.Style.props" />
    <None Include="Elements.Style.targets"
          Pack="true" PackagePath="buildTransitive\YellowDogMan.Elements.Style.targets" />

    <!-- We package .editorconfig as a .txt, to avoid issues with dotfiles and nuget -->
    <None Include="..\.editorconfig"
          Pack="true" PackagePath="content\editorconfig.txt" />
  </ItemGroup>
</Project>