<Project>
  <PropertyGroup>
    <!--Common CSProject rules and properties here-->
    <ElementsStyeVersion>$(PackageVersion)</ElementsStyeVersion>

    <!-- These properties only apply, if the property is not set locally(in the consuming project)-->
    <Company Condition="'$(Company)' == ''">Yellow Dog Man Studios</Company>
    <Copyright Condition="'$(Copyright)' == ''">Copyright (c) Yellow Dog Man Studios s.r.o.</Copyright>
    <Authors Condition="'$(Authors)' == ''">Yellow Dog Man Studios</Authors>

    <DefaultIcon Condition="'$(PackageIcon)' == ''">true</DefaultIcon>
    <PackageIcon Condition="'$(DefaultIcon)' == 'true'">icon.png</PackageIcon>
  </PropertyGroup>

  <!-- When building Elements.Style itself -->
  <ItemGroup Condition="'$(DefaultIcon)' == 'true' AND '$(MSBuildProjectName)' == 'Elements.Style'">
    <None Include="$(MSBuildThisFileDirectory)..\Images\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <!-- When consumed as a NuGet package -->
  <ItemGroup Condition="'$(DefaultIcon)' == 'true' AND '$(MSBuildProjectName)' != 'Elements.Style'">
    <None Include="$(MSBuildThisFileDirectory)..\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <!--Automatic/Logic based rules-->
  <PropertyGroup>
    <RepositoryRoot Condition="'$(SolutionDir)' != '' AND '$(RepositoryRoot)' == ''">$(SolutionDir)</RepositoryRoot>
  </PropertyGroup>
</Project>