<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageId>YellowDogMan.Elements.Style</PackageId>
    <Description>Shared build and code style defaults for Yellow Dog Man Studios / Resonite projects.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/Yellow-Dog-Man/Elements.Style</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://yellowdogman.com/</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>codestyle, style, lint</PackageTags>

    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <DevelopmentDependency>true</DevelopmentDependency>
  </PropertyGroup>
  
  <Import Project="$(MSBuildThisFileDirectory)/Elements.Style.props"/>

  <ItemGroup>
    <!-- We MUST package these files with their full NugetPackage Name, they are named without the prefix in this repo for ease of use.-->
    <None Include="Elements.Style.props"
          Pack="true" PackagePath="buildTransitive\YellowDogMan.Elements.Style.props" />
    <None Include="Elements.Style.targets"
          Pack="true" PackagePath="buildTransitive\YellowDogMan.Elements.Style.targets" />

    <None Include="..\.editorconfig"/>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include"..\LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>

  <!--Puts the Version number on the top of the .editorconfig file in the package. Allows us to monitor what version is copied, in projects that implement-->
  <!--The escapes are ASCII so: https://www.asciitable.com/ for your convenience-->
  <Target Name="AddMetadataToEditorConfig" BeforeTargets="BeforeBuild;BeforeCompile;_GetPackageFiles">
    <PropertyGroup>
      <StampedEditorConfigPath>$(IntermediateOutputPath)stamped\.editorconfig</StampedEditorConfigPath>
      <EditorConfigContent>$([System.IO.File]::ReadAllText('$(MSBuildProjectDirectory)\..\.editorconfig').Replace(';', '%3B'))</EditorConfigContent>
    </PropertyGroup>
    <MakeDir Directories="$(IntermediateOutputPath)stamped" />
    <WriteLinesToFile File="$(StampedEditorConfigPath)" Lines="# AUTOGENERATED By YellowDogMan.Elements.Style Version: $(PackageVersion)%0A%0A$(EditorConfigContent)" Overwrite="true" />
    <ItemGroup>
      <None Remove="..\.editorconfig" />
      <None Include="$(StampedEditorConfigPath)" Pack="true" PackagePath="content\.editorconfig" />
    </ItemGroup>
  </Target>
</Project>
